### PR TITLE
feat: cookie consent dialog

### LINKED ISSUE #14: Cookie Consent Dialog
Original site uses https://www.cookieyes.com/product/cookie-consent/

Screenshot 2023-01-24 at 07 55 47
Screenshot 2023-01-24 at 07 55 54
Screenshot 2023-01-24 at 07 56 03

### PR DESCRIPTION
**Pull request by solaris007**
Integrate Cookie consent dialog with customization. Provide example hooks for enabling/disabling analytics based on cookie preferences. Add internationalization.

Fix #14

Test URLs:
- Before: https://main--elco-aerotop-sg--hlxsites.hlx.page/de/
- After: https://14-cookie-consent-dialog--elco-aerotop-sg--hlxsites.hlx.page/de/

### CODE REVIEW

**Comment by solaris007** [comment]
Screenshot 2023-01-24 at 14 06 03
Screenshot 2023-01-24 at 14 06 27
Screenshot 2023-01-24 at 14 06 51

**Comment by solaris007** [comment]
Still will have to fix CLS issue from LHS.

**Comment by solaris007** [comment]
cannot reproduce CLS

Screenshot 2023-01-24 at 14 37 39

**Review by cuzuco2 — DISMISSED** [review]

**Comment by ekremney** [comment]
A few comments:

- Dialog box doesn't close when I click on the text "Zustimmen"
- After I click on "Zustimmen" I do not see anything saved in none of the local/session storages or cookie
- Design of the consent dialog doesn't look like the original one

**Comment by solaris007** [comment]
@ekremney regarding the design: the original site uses a plugin, the design of which was not adjusted to reflect the website design. i opted for using the same button and link styles as on the site. i hope that's ok.

**Review by dzehnder — APPROVED** [review]

**Pull request merged**
